version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # порт для соединений приложений и не надо называть меня чикатилой
      - "15672:15672" # порт для панели управления 1 правило моего подвала НИКОМУ не говорить о моем подвале, 2 правило моего подвала НИЗАЧТО НИ КОМУ НЕ ГОВОРИТЬ О МОЕМ ПОДВАЛЕ, 3 правило моего подвала НИНАЗЫВАТЬ МЕНЯ ЧИКАТИЛОЙ, 4 правило моего подвала - соблюдать 1 правило
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      retries: 5

  web:
    build: .
    command: >
      sh -c "while ! pg_isready -h db -U postgres; do sleep 1; done;
             uvicorn app.main:app --host 0.0.0.0 --reload"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy